export const APP_SET_DRAWER_VISIBILITY = 'APP_SET_DRAWER_VISIBILITY';
export const APP_SET_SCREEN_SIZE = 'APP_SET_SCREEN_SIZE';
export const EMAIL_ADD = 'EMAIL_ADD';
export const SEARCH_SET_IS_SEARCHING = 'SEARCH_SET_IS_SEARCHING';
export const SEARCH_SET_SEARCH_BAR_FOCUS = 'SEARCH_SET_SEARCH_BAR_FOCUS';
export const SEARCH_SET_SEARCH_BAR_VISIBILITY = 'SEARCH_SET_SEARCH_BAR_VISIBILITY';
export const SEARCH_SET_SEARCH_TEXT = 'SEARCH_SET_SEARCH_TEXT';