export const APP_SET_SCREEN_SIZE = 'APP_SET_SCREEN_SIZE';
export const APP_SET_SEARCH_BAR_VISIBILITY = 'HEADER_SET_SEARCH_BAR_VISIBILITY';
export const APP_SET_SEARCH_TEXT = 'HEADER_SET_SEARCH_TEXT';
export const EMAIL_ADD = 'EMAIL_ADD';